// Every user-visible string on the main page lives here, keyed by language.
// To remove a service, delete its entry from `services.items` in both languages.
// To add a photo later, set the `src` field in `images` (leave `null` to render nothing).

export const images = {
  hero: { src: null, alt: { ro: 'Cabinetul DishyDent', hu: 'A DishyDent rendelő' } },
  interior: { src: null, alt: { ro: 'Interiorul cabinetului DishyDent', hu: 'A DishyDent rendelő belső tere' } },
  beforeAfter: [
    { src: null, alt: { ro: 'Rezultat tratament — înainte și după', hu: 'Kezelés eredménye — előtte és utána' } },
    { src: null, alt: { ro: 'Rezultat tratament — înainte și după', hu: 'Kezelés eredménye — előtte és utána' } },
  ],
};

export const clinic = {
  name: 'DishyDent',
  addressLine1: 'Strada Aurel Filimon 24/6',
  addressLine2: '540035 Târgu Mureș, România',
  phone: '+40 799 646 666',
  phoneDisplay: '0799 646 666',
  email: 'dishydent@gmail.com',
  facebook: 'https://www.facebook.com/dishydent',
  lat: 46.5457391,
  lng: 24.5578733,
};

const content = {
  ro: {
    htmlLang: 'ro',
    meta: {
      title: 'DishyDent — Cabinet stomatologic în Târgu Mureș',
      description:
        'Servicii stomatologice complete în Târgu Mureș: consultații, igienizare, obturații, implanturi, ortodonție. Programări la telefon, mesaj sau la cabinet.',
      ogTitle: 'DishyDent — Cabinet stomatologic în Târgu Mureș',
      ogDescription: 'Tratamente dentare de la consultație până la implant. Programează cu un telefon.',
    },
    skipLink: 'Sari la conținut',
    nav: {
      services: 'Servicii',
      financing: 'Finanțare',
      contact: 'Contact',
      callNow: 'Sună acum',
      langName: 'Magyarul',
      langCode: 'HU',
    },
    hero: {
      eyebrow: 'Cabinet stomatologic · Târgu Mureș',
      headline: 'Precizie, nu presupuneri.',
      sub: 'DishyDent oferă servicii stomatologice complete în Târgu Mureș — de la controlul de rutină până la implant. Programarea se face la telefon, prin mesaj sau direct la cabinet.',
      ctaPrimary: 'Sună acum',
      ctaPrimaryAria: 'Sună la DishyDent, 0799 646 666',
      ctaSecondary: 'Vezi serviciile',
      note: 'Luni – Vineri, 08:00 – 20:00',
    },
    services: {
      eyebrow: 'Ce tratăm',
      heading: 'Servicii',
      intro: 'Un cabinet, toate etapele tratamentului — de la primul control până la lucrări protetice sau implant.',
      items: [
        {
          id: 'consultatie',
          title: 'Consultație',
          desc: 'Evaluare completă a stării dentare și un plan de tratament explicat clar, fără termeni tehnici inutili.',
        },
        {
          id: 'igienizare',
          title: 'Igienizare profesională',
          desc: 'Îndepărtarea tartrului și a plăcii bacteriene, pentru o gură sănătoasă și o respirație curată.',
        },
        {
          id: 'obturatii',
          title: 'Obturații și restaurări',
          desc: 'Tratăm cariile și refacem dinții afectați, cu materiale asortate cât mai fidel culorii naturale.',
        },
        {
          id: 'endodontie',
          title: 'Endodonție',
          desc: 'Tratament de canal atunci când infecția a ajuns la nervul dintelui, pentru a-l salva fără extracție.',
        },
        {
          id: 'extractii',
          title: 'Extracții',
          desc: 'Extragem dinții care nu mai pot fi salvați, inclusiv molarii de minte, cu anestezie adaptată fiecărui pacient.',
        },
        {
          id: 'protetica',
          title: 'Protetică dentară',
          desc: 'Coroane, punți și proteze realizate pe măsură, pentru a reda funcția masticatorie și estetica dentiției.',
        },
        {
          id: 'implanturi',
          title: 'Implanturi dentare',
          desc: 'Înlocuirea dinților lipsă cu implanturi, o soluție de durată acolo unde o punte sau o proteză nu sunt ideale.',
        },
        {
          id: 'ortodontie',
          title: 'Ortodonție',
          desc: 'Corectarea alinierii dentare la copii și adulți, cu aparate ortodontice potrivite fiecărui caz.',
        },
        {
          id: 'albire',
          title: 'Albire dentară',
          desc: 'Albire profesională, supravegheată de medic, pentru un zâmbet mai luminos fără sensibilitate inutilă.',
        },
      ],
    },
    financing: {
      eyebrow: 'Finanțare',
      heading: 'Plată în rate, prin TBI Bank',
      body: 'Un implant sau un tratament ortodontic nu trebuie plătit dintr-o singură dată. Prin TBI Bank, tratamentul poate fi achitat în rate lunare, stabilite direct la cabinet.',
      points: [
        'Aprobare rapidă, fără birocrație inutilă',
        'Rate adaptate la bugetul fiecărui pacient',
        'Disponibilă pentru implant, ortodonție și alte tratamente ample',
      ],
      disclaimer: 'Finanțare oferită prin TBI Bank. Condițiile exacte se stabilesc la cabinet, în funcție de tratament.',
    },
    contact: {
      eyebrow: 'Programări',
      heading: 'Contact',
      intro: 'Cel mai rapid mod de a face o programare este un telefon. Răspundem și pe Facebook sau la cabinet.',
      addressLabel: 'Adresă',
      hoursLabel: 'Program',
      phoneLabel: 'Telefon',
      emailLabel: 'Email',
      facebookLabel: 'Facebook',
      facebookLinkText: 'facebook.com/dishydent',
      hours: ['Luni – Vineri: 08:00 – 20:00', 'Sâmbătă – Duminică: închis'],
      mapConsent: {
        text: 'Harta este furnizată de OpenStreetMap și se încarcă doar după acceptul dumneavoastră, în secțiunea de mai jos.',
        button: 'Afișează harta',
      },
      directionsText: 'Deschide indicații rutiere',
      form: {
        heading: 'Trimite un mesaj',
        name: 'Nume',
        namePlaceholder: 'Numele dumneavoastră',
        phone: 'Telefon',
        phonePlaceholder: '07xx xxx xxx',
        message: 'Mesaj',
        messagePlaceholder: 'Cu ce vă putem ajuta?',
        submit: 'Trimite mesajul',
        submitting: 'Se trimite…',
        success: 'Mulțumim! Mesajul a fost trimis — vă contactăm în curând.',
        error: 'Mesajul nu a putut fi trimis. Vă rugăm sunați-ne direct.',
        requiredName: 'Vă rugăm introduceți numele.',
        requiredPhone: 'Vă rugăm introduceți un număr de telefon valid.',
        requiredMessage: 'Vă rugăm scrieți un mesaj scurt.',
        privacyNote: 'Datele sunt folosite exclusiv pentru a răspunde solicitării dumneavoastră.',
      },
    },
    community: {
      eyebrow: 'Comunitate',
      heading: 'Ne găsești și pe Facebook',
      body: 'Publicăm rezultate ale tratamentelor și noutăți din cabinet. Comunitatea din Târgu Mureș ne urmărește activ — alătură-te și tu.',
      statNumber: '630+',
      statLabel: 'urmăritori pe Facebook',
      cta: 'Vezi pagina de Facebook',
    },
    cookieBanner: {
      text: 'Folosim doar cookie-uri esențiale. Harta interactivă se încarcă separat, doar cu acordul dumneavoastră.',
      accept: 'Accept',
      decline: 'Refuz',
      linkText: 'Politica de cookie-uri',
    },
    footer: {
      companyLabel: 'Denumire firmă',
      companyValue: 'TODO: denumire completă SRL',
      cuiLabel: 'CUI',
      cuiValue: 'TODO',
      regComLabel: 'Reg. Com.',
      regComValue: 'TODO',
      privacyLink: 'Confidențialitate',
      cookiesLink: 'Politica de cookie-uri',
      anpcText: 'ANPC — Soluționarea Alternativă a Litigiilor',
      solText: 'Soluționarea online a litigiilor (SOL)',
      rights: (year) => `© ${year} DishyDent. Toate drepturile rezervate.`,
    },
    backHome: 'Înapoi la pagina principală',
  },

  hu: {
    htmlLang: 'hu',
    meta: {
      title: 'DishyDent — Fogászati rendelő Marosvásárhelyen',
      description:
        'Teljes körű fogászati szolgáltatások Marosvásárhelyen: konzultáció, fogkőeltávolítás, tömés, implantátum, fogszabályozás. Bejelentkezés telefonon, üzenetben vagy személyesen.',
      ogTitle: 'DishyDent — Fogászati rendelő Marosvásárhelyen',
      ogDescription: 'Fogászati kezelések a konzultációtól az implantátumig. Egy telefonhívással bejelentkezhet.',
    },
    skipLink: 'Ugrás a tartalomhoz',
    nav: {
      services: 'Szolgáltatások',
      financing: 'Finanszírozás',
      contact: 'Kapcsolat',
      callNow: 'Hívjon most',
      langName: 'Română',
      langCode: 'RO',
    },
    hero: {
      eyebrow: 'Fogászati rendelő · Marosvásárhely',
      headline: 'Pontosság, nem találgatás.',
      sub: 'A DishyDent teljes körű fogászati szolgáltatásokat nyújt Marosvásárhelyen — a rutinvizsgálattól az implantátumig. Bejelentkezés telefonon, üzenetben vagy személyesen a rendelőben.',
      ctaPrimary: 'Hívjon most',
      ctaPrimaryAria: 'Hívja a DishyDent-et, 0799 646 666',
      ctaSecondary: 'Szolgáltatásaink',
      note: 'Hétfő – Péntek, 08:00 – 20:00',
    },
    services: {
      eyebrow: 'Kezeléseink',
      heading: 'Szolgáltatások',
      intro: 'Egy rendelő, a kezelés minden lépése — az első vizsgálattól a protetikai munkáig vagy implantátumig.',
      items: [
        {
          id: 'consultatie',
          title: 'Konzultáció',
          desc: 'A fogazat teljes körű felmérése és egy világosan elmagyarázott kezelési terv, felesleges szakzsargon nélkül.',
        },
        {
          id: 'igienizare',
          title: 'Professzionális fogkőeltávolítás',
          desc: 'A fogkő és a lepedék eltávolítása az egészséges száj és a friss lehelet érdekében.',
        },
        {
          id: 'obturatii',
          title: 'Tömés és fogpótlás',
          desc: 'A szuvasodás kezelése és a sérült fogak helyreállítása, a természetes fogszínhez illesztett anyagokkal.',
        },
        {
          id: 'endodontie',
          title: 'Gyökérkezelés',
          desc: 'Gyökérkezelés akkor, amikor a fertőzés eléri a fog idegét — így a fog eltávolítás nélkül megmenthető.',
        },
        {
          id: 'extractii',
          title: 'Fogeltávolítás',
          desc: 'A már nem menthető fogak, köztük a bölcsességfogak eltávolítása, minden páciensnek megfelelő érzéstelenítéssel.',
        },
        {
          id: 'protetica',
          title: 'Fogászati protetika',
          desc: 'Egyedileg készített koronák, hidak és fogsorok, amelyek visszaadják a rágásfunkciót és a fogsor esztétikáját.',
        },
        {
          id: 'implanturi',
          title: 'Fogimplantátum',
          desc: 'A hiányzó fogak pótlása implantátummal — tartós megoldás ott, ahol a híd vagy a fogsor nem ideális.',
        },
        {
          id: 'ortodontie',
          title: 'Fogszabályozás',
          desc: 'A fogazat rendezése gyermekeknél és felnőtteknél, az adott esethez illő fogszabályozó készülékkel.',
        },
        {
          id: 'albire',
          title: 'Fogfehérítés',
          desc: 'Orvos felügyelete mellett végzett professzionális fogfehérítés, ragyogóbb mosolyért, felesleges érzékenység nélkül.',
        },
      ],
    },
    financing: {
      eyebrow: 'Finanszírozás',
      heading: 'Részletfizetés a TBI Bankon keresztül',
      body: 'Egy implantátumot vagy egy fogszabályozási kezelést nem kell egyben kifizetni. A TBI Bankon keresztül a kezelés havi részletekben törleszthető, közvetlenül a rendelőben megbeszélt feltételekkel.',
      points: [
        'Gyors jóváhagyás, felesleges ügyintézés nélkül',
        'A páciens költségvetéséhez igazított részletek',
        'Elérhető implantátumra, fogszabályozásra és más nagyobb kezelésekre',
      ],
      disclaimer: 'A finanszírozást a TBI Bank biztosítja. A pontos feltételeket a rendelőben, a kezelés függvényében határozzuk meg.',
    },
    contact: {
      eyebrow: 'Bejelentkezés',
      heading: 'Kapcsolat',
      intro: 'A leggyorsabb módja a bejelentkezésnek egy telefonhívás. Facebookon és személyesen is elérhetők vagyunk.',
      addressLabel: 'Cím',
      hoursLabel: 'Nyitvatartás',
      phoneLabel: 'Telefon',
      emailLabel: 'Email',
      facebookLabel: 'Facebook',
      facebookLinkText: 'facebook.com/dishydent',
      hours: ['Hétfő – Péntek: 08:00 – 20:00', 'Szombat – Vasárnap: zárva'],
      mapConsent: {
        text: 'A térképet az OpenStreetMap biztosítja, és csak az Ön hozzájárulása után töltődik be, az alábbi gombra kattintva.',
        button: 'Térkép megjelenítése',
      },
      directionsText: 'Útvonaltervezés megnyitása',
      form: {
        heading: 'Üzenet küldése',
        name: 'Név',
        namePlaceholder: 'Az Ön neve',
        phone: 'Telefonszám',
        phonePlaceholder: '07xx xxx xxx',
        message: 'Üzenet',
        messagePlaceholder: 'Miben segíthetünk?',
        submit: 'Üzenet küldése',
        submitting: 'Küldés…',
        success: 'Köszönjük! Az üzenetet elküldtük — hamarosan felvesszük Önnel a kapcsolatot.',
        error: 'Az üzenetet nem sikerült elküldeni. Kérjük, hívjon minket telefonon.',
        requiredName: 'Kérjük, adja meg a nevét.',
        requiredPhone: 'Kérjük, adjon meg egy érvényes telefonszámot.',
        requiredMessage: 'Kérjük, írjon egy rövid üzenetet.',
        privacyNote: 'Az adatokat kizárólag a megkeresés megválaszolására használjuk fel.',
      },
    },
    community: {
      eyebrow: 'Közösség',
      heading: 'Facebookon is megtalál minket',
      body: 'Kezelési eredményeket és rendelői híreket osztunk meg. A marosvásárhelyi közösség aktívan követ minket — csatlakozzon Ön is.',
      statNumber: '630+',
      statLabel: 'követő Facebookon',
      cta: 'Facebook oldal megtekintése',
    },
    cookieBanner: {
      text: 'Kizárólag alapvető sütiket használunk. Az interaktív térkép külön, csak az Ön hozzájárulásával töltődik be.',
      accept: 'Elfogadom',
      decline: 'Elutasítom',
      linkText: 'Cookie-szabályzat',
    },
    footer: {
      companyLabel: 'Cégnév',
      companyValue: 'TODO: teljes cégnév',
      cuiLabel: 'Adószám',
      cuiValue: 'TODO',
      regComLabel: 'Cégjegyzékszám',
      regComValue: 'TODO',
      privacyLink: 'Adatvédelem',
      cookiesLink: 'Cookie-szabályzat',
      anpcText: 'ANPC — Alternatív Vitarendezés',
      solText: 'Online vitarendezési platform (SOL)',
      rights: (year) => `© ${year} DishyDent. Minden jog fenntartva.`,
    },
    backHome: 'Vissza a főoldalra',
  },
};

export default content;
